### ISSUE TITLE
bundle size exclude wasm files

### ISSUE THREAD

**Issue by hville** [prantlf/ecmascript-parser-benchmark#1]
in the readme
- tree-sitter@0.20.0             51.28 KB   22.81 KB   6.8 KB
- tree-sitter-javascript@0.19.0  37.99 KB   29.81 KB   2.68 KB

however, this does not include the 2 large WASM files required by tree sitter:
- the parser (tree-sitter.wasm 183kb)
- the grammar (tree-sitter-javascript.wasm 230kb)

**Comment by prantlf** [comment]
You're right, thanks for pointing this out! Yes, the parser size was suspiciously small, in comparison with the others...

I added sizes of the native libraries with the parser and JavaScript grammar. Thanks again!
